service: vue-work-life-balance

plugins:
  # - serverless-s3-deploy

provider:
  name: aws
  profile: vlewin
  stage: development
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:service}/*"

custom:
  stage: "${opt:stage, self:provider.stage}"
  bucketName: "vue-work-life-balance-${self:custom.stage}"
  assets:
     - bucket: ${self:custom.bucketName}
       files:
        - source: ./dist/
          globs: "**/*"

resources:
  Resources:
    S3WorkLifeBalanceBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: error.html

  Outputs:
    S3WorkLifeBalanceBucketOutput:
      Description : "S3 Website Bucket URL"
      Value:
        Fn::GetAtt: [S3WorkLifeBalanceBucket, DomainName]
